language: objective-c
rvm: system
install:
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future bundle install
script:
  - bundle exec foodcritic -f any -f ~FC004 -f ~FC005 -f ~FC015 -f ~FC017 site-cookbooks
